"""CATEGORIES ENDPOINTS.

APIRouter = FastAPI's version of a Flask Blueprint.
Depends(get_db) = FastAPI gives each route an open session and closes it afterwards.
"""
from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from fastapi_app.database import get_db
from fastapi_app.models import Category
from fastapi_app.schemas import CategoryCreate, CategoryOut, CategoryUpdate
from fastapi_app.security import api_key_required

router = APIRouter(prefix="/categories", tags=["categories"],
                   dependencies=[Depends(api_key_required)])   # applies to ALL its routes


def get_or_404(db: Session, category_id: int) -> Category:
    category = db.get(Category, category_id)
    if category is None:
        raise HTTPException(status_code=404, detail="Categoría no encontrada")
    return category


@router.get("", response_model=list[CategoryOut])
def index(db: Session = Depends(get_db)):
    return db.scalars(select(Category).order_by(Category.name)).all()


@router.get("/{category_id}", response_model=CategoryOut)
def show(category_id: int, db: Session = Depends(get_db)):
    return get_or_404(db, category_id)


@router.post("", response_model=CategoryOut, status_code=status.HTTP_201_CREATED)
def create(data: CategoryCreate, db: Session = Depends(get_db)):
    # "data" already arrives VALIDATED: if the JSON was wrong, FastAPI answered 422 by itself
    if db.scalar(select(Category).where(Category.name == data.name)):
        raise HTTPException(status_code=422, detail="Ya existe una categoría con ese nombre")
    category = Category(**data.model_dump())
    db.add(category)
    db.commit()
    db.refresh(category)          # reloads it (gets the id generated by the DB)
    return category


@router.put("/{category_id}", response_model=CategoryOut)
def update(category_id: int, data: CategoryUpdate, db: Session = Depends(get_db)):
    category = get_or_404(db, category_id)
    for field, value in data.model_dump(exclude_unset=True).items():   # only what came
        setattr(category, field, value)
    db.commit()
    return category


@router.delete("/{category_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete(category_id: int, db: Session = Depends(get_db)):
    category = get_or_404(db, category_id)
    if category.products:
        raise HTTPException(status_code=409, detail="Tiene productos, no se puede eliminar")
    db.delete(category)
    db.commit()
    return Response(status_code=status.HTTP_204_NO_CONTENT)
